---
name: BioPerl-network
version: 1.005009_002
author:
  - 'BioPerl Team <bioperl-l@bioperl.org>'
abstract: 'BioPerl-network - package for biological networks'
license: perl
resources:
  license: http://dev.perl.org/licenses/
requires:
  Graph: 0.86
  perl: 5.6.1
optional_features:
  Bio::Graph::IO::psi:
    description: parsing PSI XML
    requires:
      XML::Twig: 3.22
dynamic_config: 1
provides:
  Bio::Network::Edge:
    file: Bio/Network/Edge.pm
    version: 1.005009_002
  Bio::Network::IO:
    file: Bio/Network/IO.pm
    version: 1.005009_002
  Bio::Network::IO::dip_tab:
    file: Bio/Network/IO/dip_tab.pm
    version: 1.005009_002
  Bio::Network::IO::psi10:
    file: Bio/Network/IO/psi10.pm
    version: 1.005009_002
  Bio::Network::IO::psi25:
    file: Bio/Network/IO/psi25.pm
    version: 1.005009_002
  Bio::Network::IO::psi::intact:
    file: Bio/Network/IO/psi/intact.pm
    version: 1.005009_002
  Bio::Network::Interaction:
    file: Bio/Network/Interaction.pm
    version: 1.005009_002
  Bio::Network::Node:
    file: Bio/Network/Node.pm
    version: 1.005009_002
  Bio::Network::ProteinNet:
    file: Bio/Network/ProteinNet.pm
    version: 1.005009_002
generated_by: Module::Build version 0.3
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
