---
name: bioperl-network
version: 1.005002005
author:
  - 'Bioperl Team <bioperl-l@bioperl.org>'
abstract: 'bioperl-network - package for biological networks'
license: artistic
resources:
  license: http://opensource.org/licenses/artistic-license.php
requires:
  Bio::Root::Version: 1.5.2
  Graph: 0.8
  perl: 5.6.1
optional_features:
  Bio::Graph::IO::psi:
    description: parsing PSI XML
    requires:
      XML::Twig: 3.22
dynamic_config: 1
provides:
  Bio::Network::Edge:
    file: Bio/Network/Edge.pm
    version: 1.005002005
  Bio::Network::IO:
    file: Bio/Network/IO.pm
    version: 1.005002005
  Bio::Network::IO::dip_tab:
    file: Bio/Network/IO/dip_tab.pm
    version: 1.005002005
  Bio::Network::IO::psi:
    file: Bio/Network/IO/psi.pm
    version: 1.005002005
  Bio::Network::IO::psi::intact:
    file: Bio/Network/IO/psi/intact.pm
    version: 1.005002005
  Bio::Network::Interaction:
    file: Bio/Network/Interaction.pm
    version: 1.005002005
  Bio::Network::Node:
    file: Bio/Network/Node.pm
    version: 1.005002005
  Bio::Network::ProteinNet:
    file: Bio/Network/ProteinNet.pm
    version: 1.005002005
generated_by: Module::Build version 0.2805
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
