---
name: BioPerl-Network
version: 1.006000_001
author:
  - 'BioPerl Team <bioperl-l@bioperl.org>'
abstract: 'BioPerl-Network - package for biological networks'
license: perl
resources:
  license: http://dev.perl.org/licenses/
requires:
  Bio::Root::Version: 1.006001
  Graph: 0.86
  perl: v5.6.1
recommends:
  XML::Twig: 3.22
configure_requires:
  Module::Build: 0.35
dynamic_config: 1
provides:
  Bio::Network::Edge:
    file: lib/Bio/Network/Edge.pm
  Bio::Network::IO:
    file: lib/Bio/Network/IO.pm
  Bio::Network::IO::dip_tab:
    file: lib/Bio/Network/IO/dip_tab.pm
  Bio::Network::IO::psi10:
    file: lib/Bio/Network/IO/psi10.pm
  Bio::Network::IO::psi25:
    file: lib/Bio/Network/IO/psi25.pm
  Bio::Network::IO::psi::intact:
    file: lib/Bio/Network/IO/psi/intact.pm
  Bio::Network::Interaction:
    file: lib/Bio/Network/Interaction.pm
  Bio::Network::Node:
    file: lib/Bio/Network/Node.pm
  Bio::Network::ProteinNet:
    file: lib/Bio/Network/ProteinNet.pm
generated_by: Module::Build version 0.35
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
